export const types = {
    //Sync
    FILL_LEADERS_DOTA: 'FILL_LEADERS_DOTA',
    ADD_LEADERS_FILTER_PARAMETER: 'ADD_LEADERS_FILTER_PARAMETER',
    REMOVE_LEADERS_FILTER_PARAMETER: 'REMOVE_LEADERS_FILTER_PARAMETER',

    //Async
    FETCH_LEADERS_DOTA: 'FETCH_LEADERS_DOTA',
    REMOVE_LEADERS_FILTER_PARAMETER_ASYNC: 'REMOVE_LEADERS_FILTER_PARAMETER_ASYNC',
    FILTER_LEADERS_ASYNC: 'FILTER_LEADERS_ASYNC',
};
