export const types = {
    //Sync
    FILL_PROFILE: 'FILL_PROFILE',
    CLEAR_PROFILE: 'CLEAR_PROFILE',
    OPEN_TUTORIAL: 'OPEN_TUTORIAL',
    CLOSE_TUTORIAL: 'CLOSE_TUTORIAL',
    FILL_GOAL_ITEM: 'FILL_GOAL_ITEM',
    FILL_REFERRAL_CODE: 'FILL_REFERRAL_CODE',
    UPDATE_NICKNAME: 'UPDATE_NICKNAME',
    UPDATE_EMAIL: 'UPDATE_EMAIL',

    //Async
    GET_GOAL_ITEM_ASYNC: 'GET_GOAL_ITEM_ASYNC',
    GET_REFERRAL_CODE_ASYNC: 'GET_REFERRAL_CODE_ASYNC',
    UPDATE_NICKNAME_ASYNC: 'UPDATE_NICKNAME_ASYNC',
    UPDATE_EMAIL_ASYNC: 'UPDATE_EMAIL_ASYNC',
};
