export const types = {
    //Sync
    AUTHENTICATE: 'AUTHENTICATE',
    LOGOUT: 'LOGOUT',

    //Async
    LOGIN_ASYNC: 'LOGIN_ASYNC',
    AUTHENTICATE_ASYNC: 'AUTHENTICATE_ASYNC',
    LOGOUT_ASYNC: 'LOGOUT_ASYNC',
    GET_USERDATA_ASYNC: 'GET_USERDATA_ASYNC',
};
