export const types = {
    //Sync
    FILL_REWARD_STATISTICS: 'FILL_REWARD_STATISTICS',
    FILL_COUNT_STATISTICS: 'FILL_COUNT_STATISTICS',
    ADD_STATISTICS_FILTER_PARAMETER: 'ADD_STATISTICS_FILTER_PARAMETER',
    REMOVE_STATISTICS_FILTER_PARAMETER: 'REMOVE_STATISTICS_FILTER_PARAMETER',

    //Async
    FETCH_GAMES_STATISTICS_ASYNC: 'FETCH_GAMES_STATISTICS_ASYNC',
    REMOVE_STATISTICS_FILTER_PARAMETER_ASYNC: 'REMOVE_STATISTICS_FILTER_PARAMETER_ASYNC',
    ADD_STATISTICS_FILTER_PARAMETER_ASYNC: 'ADD_STATISTICS_FILTER_PARAMETER_ASYNC',
};
