export const types = {
    //Sync
    FILL_REWARD_STATISTICS: 'FILL_REWARD_STATISTICS',
    FILL_COUNT_STATISTICS: 'FILL_COUNT_STATISTICS',

    //Async
    FETCH_GAMES_STATISTICS_ASYNC: 'FETCH_GAMES_STATISTICS_ASYNC',
};
