export const types = {
    //Sync
    FILL_AVAILABLE_BONUSES: 'FILL_AVAILABLE_BONUSES',

    //Async
    FETCH_AVAILABLE_BONUSES_ASYNC: 'FETCH_AVAILABLE_BONUSES_ASYNC',
    ACTIVATE_ALL_BONUSES_ASYNC: 'ACTIVATE_ALL_BONUSES_ASYNC',
    ACTIVATE_BONUS_ASYNC: 'ACTIVATE_BONUS_ASYNC',
};
