export const types = {
    START_FETCHING: 'START_FETCHING',
    STOP_FETCHING: 'STOP_FETCHING',
    SHOW_SUCCESS_LABEL: 'SHOW_SUCCESS_LABEL',
    SHOW_ERROR_LABEL: 'SHOW_ERROR_LABEL',
    HIDE_SUCCESS_LABEL: 'HIDE_SUCCESS_LABEL',
    HIDE_ERROR_LABEL: 'HIDE_ERROR_LABEL',
    EMIT_ERROR: 'EMIT_ERROR',
};
