export const types = {
    START_FETCHING: 'START_FETCHING',
    STOP_FETCHING: 'STOP_FETCHING',
    SHOW_SUCCESS_PURCHASE_LABEL: 'SHOW_SUCCESS_PURCHASE_LABEL',
    SHOW_ERROR_MARKET_LABEL: 'SHOW_ERROR_MARKET_LABEL',
    HIDE_SUCCESS_PURCHASE_LABEL: 'HIDE_SUCCESS_PURCHASE_LABEL',
    HIDE_ERROR_MARKET_LABEL: 'HIDE_ERROR_MARKET_LABEL',
    SHOW_ERROR_PASSWORD_RESET_LABEL: 'SHOW_ERROR_PASSWORD_RESET_LABEL',
    HIDE_ERROR_PASSWORD_RESET_LABEL: 'HIDE_ERROR_PASSWORD_RESET_LABEL',
    SHOW_SUCCESS_PASSWORD_RESET_LABEL: 'SHOW_SUCCESS_PASSWORD_RESET_LABEL',
    HIDE_SUCCESS_PASSWORD_RESET_LABEL: 'HIDE_SUCCESS_PASSWORD_RESET_LABEL',
    EMIT_ERROR: 'EMIT_ERROR',
};
