export const types = {
    //Sync
    FILL_MARKET_ITEMS: 'FILL_MARKET_ITEMS',
    FILL_USER_ITEMS: 'FILL_USER_ITEMS',

    //Async
    FETCH_MARKET_ITEMS_ASYNC: 'FETCH_MARKET_ITEMS_ASYNC',
    FETCH_USER_ITEMS_ASYNC: 'FETCH_USER_ITEMS_ASYNC',
    BUY_ITEM_ASYNC: 'BUY_ITEM_ASYNC',
};
