export const types = {
    //Sync
    FILL_MARKET_ITEMS: 'FILL_MARKET_ITEMS',
    FILL_USER_ITEMS: 'FILL_USER_ITEMS',
    FILL_GIFT_CODE: 'FILL_GIFT_CODE',
    ADD_FILTER_PARAMETER: 'ADD_FILTER_PARAMETER',
    REMOVE_FILTER_PARAMETER: 'REMOVE_FILTER_PARAMETER',

    //Async
    FETCH_MARKET_ITEMS_ASYNC: 'FETCH_MARKET_ITEMS_ASYNC',
    FETCH_USER_ITEMS_ASYNC: 'FETCH_USER_ITEMS_ASYNC',
    BUY_ITEM_ASYNC: 'BUY_ITEM_ASYNC',
    ACTIVATE_ITEM_ASYNC: 'ACTIVATE_ITEM_ASYNC',
    FILTER_MARKET_ITEMS_ASYNC: 'FILTER_MARKET_ITEMS_ASYNC',
    FILTER_USER_ITEMS_ASYNC: 'FILTER_USER_ITEMS_ASYNC',
    REMOVE_FILTER_PARAMETER_ASYNC: 'REMOVE_FILTER_PARAMETER_ASYNC',
};
